In [2]:
import pandas as pd
import numpy as np
import sys
import matplotlib.pyplot as plt
import unittest
import sqlite3
import db

pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)

In [3]:
#which python I used:
print("You are using Python {}.{}.".format(sys.version_info.major, sys.version_info.minor))

You are using Python 3.7.

I create a sqlite database from a csv file in my folder. Then I query this database and create a csv in my notebook.

In [4]:
#Initialize class to create databases for train and ideal
y = db.database()

#make train db
y.training_db()

#make ideal db
y.ideal_db()

#load in pandas df:
conn_train = sqlite3.connect('train.db')
conn_ideal = sqlite3.connect('ideal.db')

train = pd.read_sql_query("SELECT * FROM train", conn_train)
ideal = pd.read_sql_query("SELECT * FROM ideal", conn_ideal)

print(train.shape,
      ideal.shape)

(400, 5) (400, 51)

In [5]:
train.head()

      x         y1         y2         y3         y4
0 -20.0 -5832.4746 -23995.062  20.146387 -8019.7290
1 -19.9 -5735.4526 -23636.361  19.725082 -7900.1084
2 -19.8 -5640.1460 -23282.260  20.013353 -7781.9330
3 -19.7 -5545.7000 -22930.621  19.511282 -7665.3823
4 -19.6 -5452.1196 -22583.277  20.173714 -7549.1030

In [6]:
ideal.head()

      x        y1        y2        y3        y4        y5        y6        y7        y8        y9        y10   y11   y12   y13   y14    y15     y16     y17     y18     y19     y20       y21       y22       y23        y24        y25       y26        y27       y28       y29       y30   y31       y32        y33       y34   y35    y36   y37       y38        y39        y40        y41        y42       y43       y44        y45       y46       y47       y48       y49       y50
0 -20.0 -0.912945  0.408082  9.087055  5.408082 -9.087055  0.912945 -0.839071 -0.850919  0.816164  18.258905 -20.0 -58.0 -45.0  20.0  13.00  400.00 -400.00  800.00  410.00  289.00 -8000.000  8000.000  8000.000 -16000.000 -23995.000 -5832.000  10648.000 -8020.000 -7600.000 -8795.000  20.0  4.472136  20.124610 -0.746414  10.0  100.0 -20.0 -1.321027  399.08707  899.59190 -40.456474  40.204040  2.995732 -0.008333  12.995732  5.298317 -5.298317 -0.186278  0.912945  0.396850
1 -19.9 -0.867644  0.497186  9.132356  5.497186 -9.132356  0.867644 -0.865213  0.168518  0.994372  17.266117 -19.9 -57.7 -44.8  19.9  12.95  396.01 -396.01  792.02  406.01  285.61 -7880.599  7880.599  7880.599 -15761.198 -23636.797 -5735.339  10503.459 -7900.499 -7484.589 -8667.619  19.9  4.460942  20.025234 -0.620450   9.9   99.5 -19.9 -1.364830  395.14236  893.51280 -40.233820  40.048590  2.990720 -0.008340  12.990720  5.293305 -5.293305 -0.215690  0.867644  0.476954
2 -19.8 -0.813674  0.581322  9.186326  5.581322 -9.186326  0.813674 -0.889191  0.612391  1.162644  16.110740 -19.8 -57.4 -44.6  19.8  12.90  392.04 -392.04  784.08  402.04  282.24 -7762.392  7762.392  7762.392 -15524.784 -23282.176 -5639.752  10360.232 -7782.192 -7370.352 -8541.472  19.8  4.449719  19.925863 -0.475739   9.8   99.0 -19.8 -1.394996  391.22632  887.45870 -40.006836  39.890660  2.985682 -0.008347  12.985682  5.288267 -5.288267 -0.236503  0.813674  0.549129
3 -19.7 -0.751573  0.659649  9.248426  5.659649 -9.248426  0.751573 -0.910947 -0.994669  1.319299  14.805996 -19.7 -57.1 -44.4  19.7  12.85  388.09 -388.09  776.18  398.09  278.89 -7645.373  7645.373  7645.373 -15290.746 -22931.120 -5545.233  10218.313 -7665.073 -7257.283 -8416.553  19.7  4.438468  19.826498 -0.316436   9.7   98.5 -19.7 -1.411223  387.33844  881.43036 -39.775787  39.729824  2.980619 -0.008354  12.980619  5.283204 -5.283204 -0.247887  0.751573  0.612840
4 -19.6 -0.681964  0.731386  9.318036  5.731386 -9.318036  0.681964 -0.930426  0.774356  1.462772  13.366487 -19.6 -56.8 -44.2  19.6  12.80  384.16 -384.16  768.32  394.16  275.56 -7529.536  7529.536  7529.536 -15059.072 -22583.607 -5451.776  10077.696 -7549.136 -7145.376 -8292.856  19.6  4.427189  19.727139 -0.147038   9.6   98.0 -19.6 -1.413350  383.47803  875.42860 -39.540980  39.565693  2.975530 -0.008361  12.975530  5.278115 -5.278115 -0.249389  0.681964  0.667902